### ISSUE TITLE
working?

### ISSUE THREAD

**Issue by master88wi** [corot-scrapyard/android_device_xiaomi_corot-TWRP#1]
hello
working on
xiaomi 13t pro?

**Comment by Google20202** [comment]
> hello working on xiaomi 13t pro?

K60Ultra

**Comment by Google20202** [comment]
Waiting for TWRP update

**Comment by babybitter** [comment]
> > 您好在小米 13T Pro 上工作？
> 
> K60超

Sorry for not replying to your message in a timely manner. The image is currently not working properly. If you want to join this project, you can contact me on TG
